# Asynchronous
> 回调函数、Generator生成器、promise、async和await、定时器函数

## 1.1 SetTimeout

```js
      function printHello() {
          console.log("Hello")
      }
      setTimeout(printHello, 0)
      console.log("Which is first?")
      //Which is first?
      //Hello
```

## 1.2 promise

![asychronous.png](https://media.haochen.me/asychronous.png)
> 1. promise是JavaScript特殊的内置对象，当调用浏览器中的API时，返回一个promise对象。
> 
> 2. promise相当于是我们想从浏览器中获取的数据的占位符
> 
> 3. 使用.then方法可以实现附加功能 —— 延迟运行直到global()运行完毕
> 
> 4. promise会自动触发功能，从浏览器获得的数据会作为函数的参数/输入

### 1.2.1 How to use promise?
Use a promise to divide some numbers
```js
function divide(a, b) {
    return new Promise((resolve, reject) => {
        if(b === 0) {
            reject("You can't divide by 0")
            //防止继续执行resolve(a, b)
            return
        }
        resolve(a / b)
    })
}
divide(10, 0).then((value) => {
    console.log(`Division success: ${value}`)
}).catch(error => console.log(error))
```




### 1.2.2 under the hood of .then
调用promise的then方法，是将传进的参数函数放入promise的unfulfilled数组中，即储存我们想要自动调用的函数。

当promise的value被获取到时，value会作为函数的参数，将函数推入Microtask Queue微任务队列中。


### 1.2.3 How to run?
```js
function display(data) {console.log(data)}
function printHello() {console.log('Hello')}
function blockFor300ms() {/*blocks js thread for 300ms with long for loop*/}
setTimeout(printHello, 0)
const futureData = fetch('https://twitter.com')
futureData.then(display)
blockFor300ms()
console.log("Me first!")
```
![IMG_20220616_174510.jpg](https://media.haochen.me/IMG_20220616_174510.jpg)
![fj.jpg](https://media.haochen.me/fj.jpg)
1. Promise接受一个回调函数作为参数，回调函数又接受resolve和reject作为两个参数。
```js
//实例化promise对象
const p = new Promise(function (resolve, reject) {
    setTimeout(() => {
        let data = "用户数据库中的数据"
        resolve(data)
    }, 1000);
})

```
2. 调用promise对象的then方法

promise的then方法接受两个函数类型的参数，分别接受一个参数：
> 成功的形参：value
> 失败的形参：reason
```js
let p = new Promise(function (resolve, reject) {
    setTimeout(() => {
        let data = "用户数据库中的数据"
        resolve(data)
    }, 1000);
})
//如果异步代码调用了resolve()则表示成功
//那么then方法就会执行第一个回调函数的代码
p.then(function(value) {
    console.log(value) //'用户数据库中的数据'
}, function(reason) {
    console.log(reason)
})
```

```js
let p = new Promise(function (resolve, reject) {
    setTimeout(() => {
        let error = '数据读取失败'
        reject(error)
    }, 1000);
})
//如果异步代码调用了reject()则表示失败
//那么then方法就会执行第二个回调函数的代码
p.then(function(value) {
    console.log(value) 
}, function(reason) {
    console.log(reason) //'数据读取失败'
})
```


## 1.3 promise读取文件
```js
//1. 引入js模块
const fs = require('fs')
//2. 调用方法读取文件
// fs.readFile('./☘☘Keep healthy.md', (error, data) => {
//     //如果失败则抛出错误
//     if(error) {
//         throw error
//     }
//     //如果成功则输出内容
//     console.log(data.toString())
// })
//3. 使用Promise封装
const p = new Promise(function(resolve, reject) {
    fs.readFile('./☘☘Keep healthy.md', (error, data) => {
        //如果失败
        if(error) reject(error)
        //如果成功
        resolve(data)
    })
})
p.then((value) => {
    console.log(value.toString())
}, (reason) => {    
    console.log('读取失败！')
})
```

## 1.4 then方法
> then方法的返回结果是Promise对象，对象状态由**回调函数**的执行状态决定。
> 
> 如果回调函数中返回的结果是非promise类型的属性，状态为成功，返回值为对象的成功的值

```js
const p = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('success')
    }, 1000);
})
const result = p.then((value) => {
    console.log(value)
    //1. 返回非promise类型
    // return 'hello'
    //2. 返回promise对象
    //由promise中resolve/reject决定
    return new Promise((resolve, reject) => {
        reject('NO')
    })
    //3. 抛出错误
    throw new Error('出错啦')
}, (reason) => {
    
})
console.log(result)
```

### 1.4.1 then的链式调用
> 通过链式调用来避免callback hell
```js
p.then((value) => {

}, (reason) => {

})
.then((value) => {

}, (reason) => {

})
```

```js
const p = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('success')
    }, 1000);
})
const result = p.then((value) => {
  return new Promise((resolve, reject) => {
    resolve('the first one')
  })
}).then((value) => {
  return new Promise((resolve, reject) => {
    resolve('the second one')
  })
})
console.log(result) //the second one
```


### 1.4.2 then链式调用读取文件
```js
const fs = require('fs')
const p = new Promise((resolve, reject) => {
  fs.readFile('./☆★Daily tasks.md', (error, data1) => {
    if(error) reject(error)
    resolve(data1)
  })
})
//此处的value是data1
p.then((value) => {
    return new Promise((resolve, reject) => {
        fs.readFile('./☘☘Keep healthy.md', (error, data2) => {
            resolve([value, data2])
        })
    })
    //此处的value是[data1, data2]
}).then((value) => {
    return new Promise((resolve, reject) => {
        fs.readFile('./☘☘Keep healthy.md', (error, data3) => {
            value.push(data3)
            resolve(value)
        })
    })
}).then((value) => {
    // console.log(value.toString())同下
    console.log(value.join('\r\n'))
})

```

## 1.5 catch方法
> catch方法是语法糖，它省略了then方法的第一个参数 —— value作为参数的回调函数。
```js
const p = new Promise((resolve, reject) => {
    setTimeout(() => {
        reject('出错啦')
    }, 1000);
})
// p.then((value) => {}, (reason) => {
//     console.error(reason)
// })
p.catch((reason) => {
    console.warn(reason)
})
```

# 2. async和await
## 2.1 async
> async函数的返回值为promise对象，promise对象的结果由async函数执行的返回值决定。
```js
async function fn() {
    return new Promise((resolve, reject) => {
        resolve() //返回的结果是成功
        //reject() //返回的结果是失败
    })
}
const result = fn()
console.log(result)
/*
如果返回的是非promise类型的值，则返回的结果是成功
如果抛出错误throw new error，则返回的结果是失败
*/

result.then((value) => {
    console.log(value)
}, (reason) => {
    console.warn(reason)
})
```


## 2.2 await
> 1. await必须写在async函数中
> 2. await右侧表达式一般为promise对象
> 3. await返回的是promise成功的值
> 4. 如果await的promise失败了，就会抛出异常，需要try...catch来处理

```js
const awaitP = new Promise((resolve, reject) => {
    reject('失败')
})
async function fn() {
    try{
        let result = await awaitP
        console.log(result) 
    } catch(e) {
        console.log(e)
    }

}
//调用函数
fn()
```

## 2.3 async和await结合读取文件
```js
const fs = require('fs')
function fn1() {
    return new Promise((resolve, reject) => {
        fs.readFile('./☆★Daily tasks.md', (error, data1) => {
            if(error) reject(error)
            resolve(data1)
  })
})
}

function fn2() {
    return new Promise((resolve, reject) => {
        fs.readFile('./☘☘Keep healthy.md', (error, data2) => {
            if(error) reject(error)
            resolve(data2)
        })
    })
}
//声明一个async函数
async function main() {
    let dailyTask = await fn1()
    let keepHealthy = await fn2()
    console.log(dailyTask.toString())
    console.log(keepHealthy.toString())
}
main()
```

## 2.4 使用await的例子
```js
let a = 0
let b = async () => {
  a = a + await 10
  console.log('2', a) 
}
b()
a++
console.log('1', a) 
// -> '1' 1
// -> '2' 10
```
1. 首先函数b执行，由于await是异步操作，所以await后面的值被promise.resolve()包装成promise对象，之后去执行函数外的同步代码。
2. 同步代码执行完毕后再开始执行异步代码，将保存下来的值拿出来使用，此时a = 10


# 3. requestAnimationFrame❓

# 4. 实现一个promise ❓

# 5. 进程与线程
两个名词都是**CPU工作时间片**的一个描述
- 进程描述了CPU在运行指令及加载和保存上下文所需的时间，放在应用上来说就代表了一个程序
- 线程是进程中更小的单位，描述了执行一段指令所需的时间。

当你打开一个Tab页时，其实就是创建了一个进程，一个进程可以有多个线程，比如渲染线程，JS引擎线程，HTTP请求线程。当你发起请求时，其实是创建了一个线程，当请求结束后，该线程可能会被销毁。

在执行JS线程的时候可能会阻止UI渲染，这说明两个线程是**互斥**的。这其中的原因是JS可以修改DOM，如果在 JS 执行的时候 UI 线程还在工作，就可能导致不能安全的渲染 UI。这是单线程的一个好处，可以节省内存，节约上下文切换时间。

